language: node_js
node_js:
  - "10.14.1"

before_install:
  - npm i -g npm@6.7.0

addons:
  sonarcloud:
    organization: "kth130-github"
    token:
      secure: $SONAR

script:
  - sonar-scanner
  - npm test

deploy:
  provider: heroku
  api_key:
secure: $SECURE
  app: tmrest
